In [1]:
import pandas as pd
from IPython.display import Javascript
from IPython.core.display import display
from IPython.core.display import HTML

In [2]:
#  Datasets
df_confirmed= pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
df_deaths = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
df_recovered = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')

In [3]:
#lets group countries
conf_df_grouped = df_confirmed.groupby('Country/Region')[df_confirmed.columns[4:]].sum().reset_index()
deaths_df_grouped = df_deaths.groupby('Country/Region')[df_deaths.columns[4:]].sum().reset_index()
recv_df_grouped = df_recovered.groupby('Country/Region')[df_recovered.columns[4:]].sum().reset_index()

In [4]:
#Get flag urls
country_flags = pd.read_csv('country_flags_url.csv')
country_flags.head(2)

  Country Name                                   Image URL
0       Angola  https://www.countryflags.io/ao/flat/64.png
1      Burundi  https://www.countryflags.io/bi/flat/64.png

In [5]:
#Lets insert flags on data
deaths_df_grouped.insert(1,'Flag URL','')
conf_df_grouped.insert(1,'Flag URL','')
recv_df_grouped.insert(1,'Flag URL','')
deaths_df_grouped.head()

,Country/Region,Flag URL,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,6/5/20,6/6/20,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20
0,Afghanistan,,0,0,0,0,0,0,0,0,...,309,327,357,369,384,405,426,446,451,471
1,Albania,,0,0,0,0,0,0,0,0,...,33,34,34,34,34,34,35,36,36,36
2,Algeria,,0,0,0,0,0,0,0,0,...,690,698,707,715,724,732,741,751,760,767
3,Andorra,,0,0,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,51,51
4,Angola,,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,5,5,6,6

In [6]:
flag = country_flags[country_flags['Country Name']=="Denmark"]['Image URL']
flag = list(flag)[0]
flag

'https://www.countryflags.io/dk/flat/64.png'

In [7]:
countries_infected = df_confirmed['Country/Region'].unique()

In [8]:
#insert url on the Countries
flags_unk = []
for cnt in countries_infected:
    flag = country_flags[country_flags['Country Name']==cnt]['Image URL']
    flag = list(flag)
    if flag:
        index = conf_df_grouped[conf_df_grouped['Country/Region']==cnt].index
        conf_df_grouped.at[index,'Flag URL']=flag[0]
    else:
        flags_unk.append(cnt)

for cnt in countries_infected:
    flag = country_flags[country_flags['Country Name']==cnt]['Image URL']
    flag = list(flag)
    if flag:
        index = deaths_df_grouped[deaths_df_grouped['Country/Region']==cnt].index
        deaths_df_grouped.at[index,'Flag URL']=flag[0]

    
for cnt in countries_infected:
    flag = country_flags[country_flags['Country Name']==cnt]['Image URL']
    flag = list(flag)
    if flag:
        index = recv_df_grouped[recv_df_grouped['Country/Region']==cnt].index
        recv_df_grouped.at[index,'Flag URL']=flag[0]

In [9]:
#SAve the updated version
conf_df_grouped.to_csv('covid_19_race_bar_conf.csv', index=False)
deaths_df_grouped.to_csv('covid_19_race_bar_death.csv', index=False)
recv_df_grouped.to_csv('covid_19_race_bar_recv.csv', index=False)

In [10]:
country_flags = pd.read_csv('country_flags_url.csv')
country_flags.head()

   Country Name                                   Image URL
0        Angola  https://www.countryflags.io/ao/flat/64.png
1       Burundi  https://www.countryflags.io/bi/flat/64.png
2         Benin  https://www.countryflags.io/bj/flat/64.png
3  Burkina Faso  https://www.countryflags.io/bf/flat/64.png
4      Botswana  https://www.countryflags.io/bw/flat/64.png

In [11]:
cnt_ext = {'US':'https://www.countryflags.io/us/flat/64.png','Iran':'https://www.countryflags.io/ir/flat/64.png',
           'United Kingdom':'https://www.countryflags.io/gb/flat/64.png', 
           'Korea, South':'https://www.countryflags.io/kr/flat/64.png'}
for cnt,url in cnt_ext.items():
        index = deaths_df_grouped[deaths_df_grouped['Country/Region']==cnt].index
        deaths_df_grouped.at[index,'Flag URL']=url
        index = conf_df_grouped[conf_df_grouped['Country/Region']==cnt].index
        conf_df_grouped.at[index,'Flag URL']=url
        index = recv_df_grouped[recv_df_grouped['Country/Region']==cnt].index
        recv_df_grouped.at[index,'Flag URL']=url

In [12]:
deaths_df_grouped.head()

,Country/Region,Flag URL,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,6/5/20,6/6/20,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20
0,Afghanistan,https://www.countryflags.io/af/flat/64.png,0,0,0,0,0,0,0,0,...,309,327,357,369,384,405,426,446,451,471
1,Albania,https://www.countryflags.io/al/flat/64.png,0,0,0,0,0,0,0,0,...,33,34,34,34,34,34,35,36,36,36
2,Algeria,https://www.countryflags.io/dz/flat/64.png,0,0,0,0,0,0,0,0,...,690,698,707,715,724,732,741,751,760,767
3,Andorra,https://www.countryflags.io/ad/flat/64.png,0,0,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,51,51
4,Angola,https://www.countryflags.io/ao/flat/64.png,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,5,5,6,6

In [13]:
#data included flags
conf_df_grouped.to_csv('covid_19_race_bar_conf.csv', index=False)
deaths_df_grouped.to_csv('covid_19_race_bar_death.csv', index=False)
recv_df_grouped.to_csv('covid_19_race_bar_recv.csv', index=False)

In [14]:
from IPython.display import Javascript
from IPython.core.display import display
from IPython.core.display import HTML

In [15]:
HTML("""
<div class="flourish-embed flourish-bar-chart-race" data-src="visualisation/2476141" data-url="https://flo.uri.sh/visualisation/2476141/embed"><script src="https://public.flourish.studio/resources/embed.js"></script></div>""")